# Generated by Django 3.1 on 2020-09-02 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import flatnye.api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date creation')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de mise ajour')),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
        migrations.CreateModel(
            name='AjoutPanier',
            fields=[
                ('timemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.timemodel')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, null=True)),
                ('type_ajout', models.CharField(blank=True, max_length=1, null=True)),
            ],
            bases=('api.timemodel',),
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('timemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.timemodel')),
                ('titre', models.CharField(blank=True, max_length=150, null=True)),
                ('localisation', models.CharField(blank=True, max_length=150, null=True, verbose_name='coordonées GPS')),
                ('ville', models.CharField(blank=True, max_length=50, null=True)),
                ('quartier', models.CharField(blank=True, max_length=50, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True, verbose_name='Superficie, taille')),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('prix', models.FloatField(blank=True, null=True)),
                ('date_mise_en_ligne', models.DateTimeField(auto_now_add=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('T', 'Terrain'), ('V', 'Villa'), ('M', 'Maison'), ('A', 'Appartement'), ('C', 'Chambre')], max_length=1, null=True)),
                ('categorie', models.CharField(blank=True, choices=[('L', 'Location'), ('V', 'Vente')], max_length=1, null=True)),
                ('etat', models.CharField(blank=True, choices=[('V', 'Vendu'), ('R', 'Reservé'), ('L', 'Loué')], max_length=1, null=True)),
                ('est_valide', models.BooleanField(blank=True, default=False, null=True)),
            ],
            bases=('api.timemodel',),
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('timemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.timemodel')),
                ('titre', models.CharField(blank=True, max_length=100, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to=flatnye.api.models.Visite.upload_fichier)),
                ('bien_viste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bien')),
            ],
            bases=('api.timemodel',),
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('timemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.timemodel')),
                ('slug', models.SlugField()),
                ('est_regle', models.BooleanField(blank=True, default=False, null=True)),
                ('bien_panier', models.ManyToManyField(through='api.AjoutPanier', to='api.Bien')),
            ],
            bases=('api.timemodel',),
        ),
        migrations.CreateModel(
            name='Notation',
            fields=[
                ('timemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.timemodel')),
                ('nombre_etoile', models.IntegerField(blank=True, choices=[(1, 'Mediocre'), (2, 'Acceptable'), (3, 'Bien'), (4, 'Tres Bien'), (5, 'Exellent')], null=True)),
                ('bien_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bien')),
            ],
            bases=('api.timemodel',),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('timemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.timemodel')),
                ('titre', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('V', 'Video'), ('P', 'Photo')], max_length=1, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to=flatnye.api.models.Media.upload_media)),
                ('bien_decrit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bien')),
            ],
            bases=('api.timemodel',),
        ),
        migrations.CreateModel(
            name='Loaction',
            fields=[
                ('timemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.timemodel')),
                ('date_paiement', models.DateTimeField(auto_now_add=True, null=True)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('bien_loue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bien')),
            ],
            bases=('api.timemodel',),
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('timemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.timemodel')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('addresse', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('contact', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('localisation', models.CharField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='User/Profile', verbose_name='Image de profile')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('api.timemodel',),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('timemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.timemodel')),
                ('contenu', models.TextField(blank=True, null=True)),
                ('bien_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bien')),
            ],
            bases=('api.timemodel',),
        ),
        migrations.AddField(
            model_name='bien',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.compte'),
        ),
        migrations.AddField(
            model_name='ajoutpanier',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bien'),
        ),
        migrations.AddField(
            model_name='ajoutpanier',
            name='bucket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.panier'),
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('timemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.timemodel')),
                ('date_achat', models.DateTimeField(auto_now_add=True, null=True)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('biens', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bien')),
                ('biens_panier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.panier')),
            ],
            bases=('api.timemodel',),
        ),
    ]
