# Generated by Django 3.1 on 2020-09-11 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200906_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=150, null=True, verbose_name="Titre de l'article")),
                ('texte', models.TextField(blank=True, null=True, verbose_name="Contenu de l'article")),
                ('etat', models.CharField(blank=True, choices=[('Pub', 'Publié'), ('Brl', 'Brouillon'), ('Anl', 'Annulé')], max_length=3, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='article_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.article'),
        ),
    ]
