# Generated by Django 3.1 on 2020-09-11 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200911_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ajoutpanier',
            old_name='article',
            new_name='bien_ajout',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='article_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.article'),
        ),
    ]
